import type { AiProfileId, Id, Money, Quarter, SectorId } from './ids';

/** Annual figures of a company (revenue and EBITDA over four quarters). */
export interface AnnualFigures {
  revenue: Money;
  ebitda: Money;
}

/**
 * An unlisted company for sale ("pépite"), generated by the M&A market. It
 * only becomes a simulated company when someone buys it.
 */
export interface TargetListing {
  /** "tgt_001". */
  id: Id;
  name: string;
  sector: SectorId;
  regionId: Id;
  /** Size relative to a starting company of its sector. */
  scale: number;
  /** Profile of the management in place (runs the company when nobody decides for it). */
  managementProfileId: AiProfileId;
  listedAt: Quarter;
  /** Withdrawn from sale at the start of this quarter. */
  expiresAt: Quarter;
  /** Price asked for 100 % of the shares. */
  askingPrice: Money;
  /** Public estimate of the annual figures (noisy). */
  estimate: AnnualFigures;
  /** Net debt of the company (public). */
  netDebt: Money;
  /** Private: the expected annual figures, revealed by a due diligence. */
  actual: AnnualFigures;
  /** Private: liability nobody declared (litigation, social debt), revealed by a due diligence. */
  hiddenLiability: Money;
}

/** Results of a due diligence, private to the buyer. */
export interface DueDiligence {
  buyerId: Id;
  /** Company id or listing id. */
  targetId: Id;
  orderedAt: Quarter;
  /** Results usable from orderedAt + 1, until this quarter (exclusive). */
  expiresAt: Quarter;
  /** Annual figures established without publication lag nor noise. */
  figures: AnnualFigures;
  netDebt: Money;
  hiddenLiability: Money;
}

/** A company taken over and being integrated into its new group. */
export interface Integration {
  companyId: Id;
  acquirerId: Id;
  startedAt: Quarter;
  /** Integration costs are charged until this quarter (exclusive). */
  until: Quarter;
  /** One-off charge still to book in the company (an undeclared liability). */
  pendingCharge: Money;
}

export interface MnaState {
  /** Unlisted companies for sale, oldest first. */
  listings: TargetListing[];
  diligence: DueDiligence[];
  integrations: Integration[];
}
