import type { Actor, RndType } from './company';
import type { Observation } from './ai';
import type { ValidationIssue } from './decisions';
import type { GameEvent, GameEventSeverity, ModifierTargetKind } from './events';
import type { GameMode, Id, ModifierKey, Money, Quarter } from './ids';
import type { HistoryStore } from './state';

export type AlertKind =
  | 'material_low' // stored material + contract deliveries below the alert cover
  | 'stockout' // demand lost last quarter for lack of finished goods
  | 'wage_below_market' // a staff group is paid under the market wage
  | 'covenant_near' // net debt / EBITDA close to the bank covenant
  | 'covenant_breached'
  | 'overdraft'
  | 'distress' // negative equity on the overdraft: bankruptcy looms
  | 'capacity_saturated'; // sales close to the line capacity

/** Generated by the engine; rendered in French by the UI from `kind` and `data`. */
export interface Alert {
  kind: AlertKind;
  severity: GameEventSeverity;
  companyId: Id;
  data?: Record<string, number | string | boolean>;
}

/** What an R&D budget of the given type would fund this quarter. */
export interface RndQuote {
  /** Current level (process: company, product: main product line). */
  level: number;
  maxLevel: number;
  /** Project in progress, if any. */
  projectId?: Id;
  progress: number;
  /** Cost of the project in progress, or of the next one. */
  cost: Money;
  /** Most the project can absorb this quarter (0 when the level is maxed out). */
  maxBudget: Money;
}

/** Prices the player is quoted for this quarter's one-shot decisions. */
export interface PlayerCosts {
  /** Cost of a new factory, by region. */
  buildSite: Record<Id, Money>;
  addLine: Money;
  modernizeLine: Money;
  /** Cash a disposal would bring, by line id and by site id. */
  saleValue: Record<Id, Money>;
  rnd: Record<RndType, RndQuote>;
}

/** What the UI shows: the player's Observation plus journal, history and alerts. */
export interface PlayerView extends Observation {
  status: 'running' | 'won' | 'lost';
  mode: GameMode;
  actor: Actor;
  alerts: Alert[];
  /** Public entries and the player's own, oldest first. */
  log: GameEvent[];
  /** Public series and the player's own company series. */
  history: HistoryStore;
  /** Value of the player's stake in its root company (price × shares held). */
  score: Money;
  /** Quotes for investments, disposals and R&D (absent once the company is gone). */
  costs?: PlayerCosts;
}

/** Deterministic estimate of a quarter under the submitted decisions. */
export interface CompanyPreview {
  companyId: Id;
  /** Output ceiling with the planned crew and the lines available this quarter. */
  outputCeiling: number;
  /** Output after production targets and available materials. */
  plannedOutput: number;
  /** Material units the production targets need, by commodity (before material limits). */
  materialNeeds: Record<Id, number>;
  expectedDemand: number;
  expectedUnitsSold: number;
  expectedRevenue: Money;
  costs: {
    materials: Money;
    wages: Money;
    hiring: Money;
    severance: Money;
    training: Money;
    marketing: Money;
    rnd: Money;
    maintenance: Money;
    logistics: Money;
    storage: Money;
    interest: Money;
  };
  capex: Money;
  disposals: Money;
  borrowing: Money;
  repayment: Money;
  installments: Money;
  expectedEbitda: Money;
  expectedCashEnd: Money;
  /** The estimate ends below zero: the overdraft would be drawn. */
  overdraftRisk: boolean;
}

export interface DecisionPreview {
  issues: ValidationIssue[];
  companies: Record<Id, CompanyPreview>;
}

export interface ReportedEvent {
  eventId: Id;
  target: { kind: ModifierTargetKind; id?: Id };
  effects: { key: ModifierKey; op: 'add' | 'mul'; value: number }[];
  durationQuarters: number;
  /** Targets the player's regions, labor pools, commodities, markets or company (or global). */
  concernsPlayer: boolean;
}

/** Planned versus actual for the player's root company over the resolved quarter. */
export interface PlayerTurnSummary {
  companyId: Id;
  quarter: Quarter;
  revenue: Money;
  ebitda: Money;
  netIncome: Money;
  cashStart: Money;
  cashEnd: Money;
  plannedOutput: number;
  unitsProduced: number;
  demand: number;
  unitsSold: number;
  lostSales: number;
  marketShare: number;
  marketShareChange: number;
  hiresRequested: number;
  hired: number;
  quits: number;
  dismissed: number;
  sharePrice: Money;
  /** Relative change over the quarter. */
  sharePriceChange: number;
  indexChange: number;
  events: ReportedEvent[];
}
