import type { Actor, RndType } from './company';
import type { Observation } from './ai';
import type { ValidationIssue } from './decisions';
import type { GameEvent, GameEventSeverity, ModifierTargetKind } from './events';
import type { GameMode, HolderId, Id, ModifierKey, Money, Quarter, SectorId } from './ids';
import type { HistoryStore } from './state';
import type { AnnualFigures } from './mna';
import type { ConsolidatedStatements } from './finance';

export type AlertKind =
  | 'material_low' // stored material + contract deliveries below the alert cover
  | 'stockout' // demand lost last quarter for lack of finished goods
  | 'wage_below_market' // a staff group is paid under the market wage
  | 'covenant_near' // net debt / EBITDA close to the bank covenant
  | 'covenant_breached'
  | 'overdraft'
  | 'distress' // negative equity on the overdraft: bankruptcy looms
  | 'capacity_saturated' // sales close to the line capacity
  | 'tech_behind' // tech: the product lags the technology frontier
  | 'maintenance_short'; // tech: too few developers off R&D for the subscribers

/** Generated by the engine; rendered in French by the UI from `kind` and `data`. */
export interface Alert {
  kind: AlertKind;
  severity: GameEventSeverity;
  companyId: Id;
  data?: Record<string, number | string | boolean>;
}

/** What an R&D budget of the given type would fund this quarter. */
export interface RndQuote {
  /** Current level (process: company, product: main product line). */
  level: number;
  maxLevel: number;
  /** Project in progress, if any. */
  projectId?: Id;
  progress: number;
  /** Cost of the project in progress, or of the next one. */
  cost: Money;
  /** Most the project can absorb this quarter (0 when the level is maxed out). */
  maxBudget: Money;
  /** Tech: developer-quarters of the project in progress, or of the next one. */
  effort?: number;
  /** Tech: most developers the project can use this quarter. */
  maxDevelopers?: number;
}

/** Equity transactions the company can make this quarter. */
export interface CapitalQuotes {
  /** Most it can pay out (cash, within its equity); 0 while distressed or in breach of covenant. */
  maxDividend: Money;
  /** Listed: price of a new share and most new shares (control of the group kept). */
  issuePrice: Money;
  maxIssue: number;
  /** Listed: price paid per share bought back and most shares this quarter. */
  buybackPrice: Money;
  maxBuyback: number;
  /** Unlisted: terms of a public offering, if it can go public now. */
  ipo?: { pricePerShare: Money; newShares: number; proceeds: Money };
}

/** Prices the player is quoted for this quarter's one-shot decisions. */
export interface PlayerCosts {
  /** Cost of a new factory, by region. */
  buildSite: Record<Id, Money>;
  addLine: Money;
  modernizeLine: Money;
  /** Cash a disposal would bring, by line id and by site id. */
  saleValue: Record<Id, Money>;
  rnd: Record<RndType, RndQuote>;
  capital: CapitalQuotes;
  /** Agri: price of a farm and farmland still for sale (hectares), by region. */
  farms?: { buy: Record<Id, Money>; landLeft: Record<Id, number>; hectares: number };
  /**
   * Tech: buildSite is the price of an office; seats of an office, free seats
   * by region, developers available for R&D this quarter, frontier of the market.
   */
  tech?: {
    seats: number;
    freeSeats: Record<Id, number>;
    developers: number;
    frontier: number;
  };
}

/** Valuation of a company the player could buy, from what the player knows. */
export interface DealQuote {
  targetId: Id;
  kind: 'listing' | 'company';
  name: string;
  sector: SectorId | 'holding';
  /** Annual figures used: the due diligence, else the published accounts or the public estimate. */
  figures: AnnualFigures;
  netDebt: Money;
  /** A due diligence of the viewed company on it is usable now (pending: results next quarter). */
  diligence: 'none' | 'pending' | 'done';
  /** Revealed by the due diligence. */
  hiddenLiability?: Money;
  /** Equity value of the whole company: multiples, DCF, range and expected control premium. */
  valuation: {
    multiples: Money;
    dcf: Money;
    low: Money;
    mid: Money;
    high: Money;
    controlPremium: number;
  };
  /** Company: share price at the start of the quarter and premium its board asks (absent: not for sale). */
  referencePrice?: Money;
  askedPremium?: number;
  /** Company: shares of the block of its controlling shareholder, and shares a tender offer would seek. */
  blockShares?: number;
  tenderShares?: number;
  /** Listing: price for 100 % (less the liability a due diligence revealed). */
  price?: Money;
  dueDiligenceCost: Money;
  /** Acquisition loan the bank would grant for it. */
  debtCapacity: Money;
}

/** A company of the player's group. */
export interface GroupCompanyView {
  companyId: Id;
  name: string;
  sector: SectorId | 'holding';
  status: 'active' | 'distressed' | 'bankrupt' | 'absorbed';
  listed: boolean;
  /** The root company of the player (the group head). */
  isRoot: boolean;
  /** Holder of the largest stake in it within the group (a company, or the player's actor). */
  parentId: HolderId;
  /** Share of its capital the group holds. */
  stake: number;
  /** Value of the group's shares (quote, or private value of an unlisted company). */
  value: Money;
  /** Cost of the stakes held by the group's companies (absent for the root company). */
  cost?: Money;
  revenue: Money;
  ebitda: Money;
  netIncome: Money;
  cash: Money;
  equity: Money;
  debt: Money;
  /** Share of it the head's shareholders own through the group (product of the stakes). */
  groupShare: number;
  /** Group share of its net income without its intra-group financial result. */
  contribution: Money;
  /** Intra-group loans it granted, and those it owes, outstanding. */
  groupLoans: Money;
  groupDebt: Money;
  /** Its stakes in other companies of the group: shares held and their value. */
  stakes: { targetId: Id; shares: number; value: Money }[];
  /** Integration under way after its takeover: until this quarter (exclusive). */
  integrationUntil?: Quarter;
}

/** An intra-group loan outstanding in the player's group. */
export interface GroupLoanView {
  lenderId: Id;
  borrowerId: Id;
  principal: Money;
  /** Annual rate this quarter (policy rate + spread). */
  rate: number;
}

/** Synergies and complexity costs of the player's group this quarter (lot 3.2). */
export interface GroupSynergiesView {
  headId: Id;
  /** Operating companies of the group (holding companies excluded). */
  members: Id[];
  subsidiaries: number;
  sectors: SectorId[];
  /** Group brand (revenue-weighted) and its weight in the brand customers see. */
  brand: number;
  sharedBrandWeight: number;
  /** Managerial load, capacity and the members' efficiency (1: no overload). */
  load: number;
  capacity: number;
  efficiency: number;
  /** Holding fees of the quarter (shared by revenue). */
  holdingFee: Money;
  /** Share of the support functions' wages saved, and the amount for the whole group. */
  supportSaving: number;
  supportSavingAmount: Money;
  /** Conglomerate discount on the holding company's sum of the parts. */
  discount: number;
  /** Volume per quarter the members contract together, by commodity (in force). */
  pooledContracts: Record<Id, number>;
}

/** What the UI shows: the player's Observation plus journal, history and alerts. */
export interface PlayerView extends Observation {
  status: 'running' | 'won' | 'lost';
  mode: GameMode;
  actor: Actor;
  alerts: Alert[];
  /** Public entries and the player's own, oldest first. */
  log: GameEvent[];
  /** Public series and the player's own company series. */
  history: HistoryStore;
  /** Value of the player's stake in its root company (share value × shares held). */
  score: Money;
  /** Quotes for investments, disposals, R&D and equity transactions (absent once the company is gone). */
  costs?: PlayerCosts;
  /** Companies of the player's group (root first). */
  groupCompanies: GroupCompanyView[];
  /** Intra-group loans between the companies of the group (and to former members). */
  groupLoans: GroupLoanView[];
  /** Consolidated accounts of the player's group, oldest first (absent: no subsidiary). */
  consolidated?: ConsolidatedStatements[];
  /** Synergies and complexity costs of the group (absent: no subsidiary). */
  synergies?: GroupSynergiesView;
  /** The root company can be put under a new holding company this quarter. */
  canCreateHolding: boolean;
  /** Companies the viewed company could buy (listings, then companies by id). */
  deals: DealQuote[];
}

/** Deterministic estimate of a quarter under the submitted decisions. */
export interface CompanyPreview {
  companyId: Id;
  /** Output ceiling with the planned crew and the lines available this quarter. */
  outputCeiling: number;
  /** Output after production targets and available materials. */
  plannedOutput: number;
  /** Material units the production targets need, by commodity (before material limits). */
  materialNeeds: Record<Id, number>;
  expectedDemand: number;
  /** Tech: units are subscriber-quarters; subscribers expected at the end of the quarter. */
  expectedUsers?: number;
  expectedUnitsSold: number;
  expectedRevenue: Money;
  costs: {
    materials: Money;
    wages: Money;
    hiring: Money;
    severance: Money;
    training: Money;
    marketing: Money;
    rnd: Money;
    maintenance: Money;
    logistics: Money;
    storage: Money;
    interest: Money;
    /** Share of the group's holding fees (lot 3.2). */
    holdingFees: Money;
  };
  capex: Money;
  disposals: Money;
  /** Net cash of the intra-group transfers at the end of the quarter (estimate). */
  groupTransfers: Money;
  borrowing: Money;
  repayment: Money;
  installments: Money;
  /** Net cash of the equity transactions (issues and offerings − dividends − buybacks). */
  equity: Money;
  /** Due diligences ordered, integration costs, an undeclared liability coming due. */
  mnaCosts: Money;
  /** Cash part of the deals (end of quarter) and acquisition loans drawn for them (estimates). */
  acquisitions: Money;
  acquisitionDebt: Money;
  expectedEbitda: Money;
  expectedCashEnd: Money;
  /** The estimate ends below zero: the overdraft would be drawn. */
  overdraftRisk: boolean;
}

export interface DecisionPreview {
  issues: ValidationIssue[];
  companies: Record<Id, CompanyPreview>;
}

export interface ReportedEvent {
  eventId: Id;
  target: { kind: ModifierTargetKind; id?: Id };
  effects: { key: ModifierKey; op: 'add' | 'mul'; value: number }[];
  durationQuarters: number;
  /** Targets the player's regions, labor pools, commodities, markets or company (or global). */
  concernsPlayer: boolean;
}

/** Planned versus actual for the player's root company over the resolved quarter. */
export interface PlayerTurnSummary {
  companyId: Id;
  quarter: Quarter;
  revenue: Money;
  ebitda: Money;
  netIncome: Money;
  cashStart: Money;
  cashEnd: Money;
  plannedOutput: number;
  unitsProduced: number;
  demand: number;
  unitsSold: number;
  lostSales: number;
  marketShare: number;
  marketShareChange: number;
  hiresRequested: number;
  hired: number;
  quits: number;
  dismissed: number;
  sharePrice: Money;
  /** Relative change over the quarter. */
  sharePriceChange: number;
  indexChange: number;
  events: ReportedEvent[];
}
